version: '3.1'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: nkey
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: n1234
    ports:
      - 27017:27017
  